FROM node:20-alpine AS builder
WORKDIR /app
COPY package*.json ./
RUN npm ci
COPY . .
ARG VITE_SUPABASE_URL
ARG VITE_SUPABASE_ANON_KEY
ARG VITE_SUPER_ADMIN_LOGIN
ARG VITE_SUPER_ADMIN_PASSWORD_HASH
ARG VITE_SIKA_SALT
ARG VITE_SIKA_MGMT_SECRET
ARG VITE_APP_URL
ARG VITE_APP_VERSION
ARG VITE_DEBUG_MODE
ENV VITE_SUPABASE_URL=$VITE_SUPABASE_URL
ENV VITE_SUPABASE_ANON_KEY=$VITE_SUPABASE_ANON_KEY
ENV VITE_SUPER_ADMIN_LOGIN=$VITE_SUPER_ADMIN_LOGIN
ENV VITE_SUPER_ADMIN_PASSWORD_HASH=$VITE_SUPER_ADMIN_PASSWORD_HASH
ENV VITE_SIKA_SALT=$VITE_SIKA_SALT
ENV VITE_SIKA_MGMT_SECRET=$VITE_SIKA_MGMT_SECRET
ENV VITE_APP_URL=$VITE_APP_URL
ENV VITE_APP_VERSION=$VITE_APP_VERSION
ENV VITE_DEBUG_MODE=$VITE_DEBUG_MODE
RUN npm run build

FROM nginx:alpine
COPY --from=builder /app/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
HEALTHCHECK --interval=30s --timeout=5s --retries=3 \
  CMD wget -q --spider http://127.0.0.1/healthz || exit 1
CMD ["nginx", "-g", "daemon off;"]
